package com.nhlstenden.jabberpoint.command;

import com.nhlstenden.jabberpoint.model.Presentation;
import com.nhlstenden.jabberpoint.model.Slide;
import com.nhlstenden.jabberpoint.model.TextItem;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.awt.*;
import java.io.File;

import static org.junit.jupiter.api.Assertions.*;

public class SaveCommandTest
{

    private static final String DUMP_FILE = "dump.xml";
    private Presentation presentation;
    private Frame frame;
    private SaveCommand saveCommand;

    @BeforeEach
    public void setUp()
    {
        presentation = new Presentation();
        frame = new Frame();
        saveCommand = new SaveCommand(presentation, frame);
    }

    @AfterEach
    public void tearDown()
    {
        // Clean up the dump file if it was created during the test to avoid polluting the workspace
        File file = new File(DUMP_FILE);
        if (file.exists())
        {
            file.delete();
        }
    }

    @Test
    public void testConstructor_validArguments_commandCreated()
    {
        assertNotNull(saveCommand);
    }

    @Test
    public void testExecute_validPresentation_fileSavedWithoutExceptions()
    {
        // Arrange
        presentation.setTitle("Test Presentation");
        Slide slide = new Slide();
        slide.append(new TextItem(1, "Test content for save command."));
        presentation.append(slide);

        // Act & Assert
        // We assert DoesNotThrow to ensure the execute method correctly traps or avoids any runtime/IO exceptions
        assertDoesNotThrow(() -> saveCommand.execute());

        // Verify that the file was actually generated by the SaveCommand
        File file = new File(DUMP_FILE);
        assertTrue(file.exists(), "The dump.xml file should have been created by the SaveCommand.");
    }
}
