name: 3. Acceptatie (A)

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-acceptance:
    runs-on: ubuntu-latest
    environment: acceptance
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "maven"

      # Bouw het JAR bestand
      - name: Package Application
        run: mvn clean package -DskipTests

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Jabberpoint-Executable
          path: target/*.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          generate_release_notes: true
          files: target/*.jar
